name: Build artifacts

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  wasm_build_web:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    container: emscripten/emsdk
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Install deps
        run: sudo apt update -y && sudo apt install -y cmake gperf

      - name: 🏗️ Build WASM for web
        working-directory: ./src/platforms/emscripten/
        run: |
          set -euo pipefail
          mkdir build
          cd build
          emcmake cmake .. -DAVM_EMSCRIPTEN_ENV=web
          emmake make -j

      - name: Vars setup
        id: setup
        run: |
          set -euo pipefail
          VERSION=$([[ $GITHUB_REF_TYPE = "tag" ]] && echo $GITHUB_REF_NAME || echo ${GITHUB_SHA::8})
          echo "fissionvm_js=FissionVM-web-${VERSION}.mjs" >> $GITHUB_OUTPUT
          echo "fissionvm_wasm=FissionVM-web-${VERSION}.wasm" >> $GITHUB_OUTPUT
          echo "artifacts_dir=src/platforms/emscripten/build/src" >> $GITHUB_OUTPUT

      - name: "Rename artifacts"
        working-directory: ${{ steps.setup.outputs.artifacts_dir }}
        run: |
          mv AtomVM.mjs "${{ steps.setup.outputs.fissionvm_js }}"
          gzip -k "${{ steps.setup.outputs.fissionvm_js }}"
          sha256sum "${{ steps.setup.outputs.fissionvm_js }}" > "${{ steps.setup.outputs.fissionvm_js }}.sha256"
          mv AtomVM.wasm "${{ steps.setup.outputs.fissionvm_wasm }}"
          gzip -k  "${{ steps.setup.outputs.fissionvm_wasm }}"
          sha256sum "${{ steps.setup.outputs.fissionvm_wasm }}" > "${{ steps.setup.outputs.fissionvm_wasm }}.sha256"

      - name: "Release (web)"
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ startsWith( github.ref_name, 'test-') }}
          fail_on_unmatched_files: true
          files: |
            ${{ steps.setup.outputs.artifacts_dir }}/${{ steps.setup.outputs.fissionvm_js }}
            ${{ steps.setup.outputs.artifacts_dir }}/${{ steps.setup.outputs.fissionvm_js }}.gz
            ${{ steps.setup.outputs.artifacts_dir }}/${{ steps.setup.outputs.fissionvm_js }}.sha256
            ${{ steps.setup.outputs.artifacts_dir }}/${{ steps.setup.outputs.fissionvm_wasm }}
            ${{ steps.setup.outputs.artifacts_dir }}/${{ steps.setup.outputs.fissionvm_wasm }}.gz
            ${{ steps.setup.outputs.artifacts_dir }}/${{ steps.setup.outputs.fissionvm_wasm }}.sha256
